[package]
name = "pdex"
version = "0.1.0"
authors = ["Phodal Huang <h@phodal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dex = "0.4.0"
memmap = "0.7.0"


[lib]
name = "pdex"
path = "src/lib.rs"
