[package]
name = "papk"
version = "0.1.0"
authors = ["Phodal Huang <h@phodal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5"
abxml = "0.8.2"
log = "0.4.11"
failure = "0.1.8"
